### ISSUE TITLE
Error: link button not pressed - definition

### ISSUE THREAD

**Issue by imsoftware** [rektdeckard/huebert#6]
Hey, i thought about "Error: link button not pressed" message. 
I think it would be better to write "Error: Hue link button not pressed". People can think link button means a button in the app. I wanted make PR, but i didn't find the message in the source code.

**Comment by rektdeckard** [comment]
That's a nice little improvement, I'll make the change right away. The reason you can't find it in code is that it's the error generated by the bridge itself.

I've also got comments that the steps to enable CORS are a bit hidden or confusing. Any suggestions on that?

**Comment by rektdeckard** [comment]
@imsoftware it's [here](https://github.com/rektdeckard/huebert/blob/b7a7a98b70a60c824deb30b4ecd23bee6feeb5b5/src/components/SettingsView.js#L50) if you want to make the change :)

**Comment by imsoftware** [comment]
@rektdeckard Thank you!
